version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fixi_postgres
    restart: always
    environment:
      POSTGRES_DB: fixi_db
      POSTGRES_USER: fixi_user
      POSTGRES_PASSWORD: fixi_pass
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixi_user -d fixi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
